import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import {
	requireLinkedEntityAccess,
	linkedEntityBelongsToOrganization,
	parseLinkedEntityQuery
} from '$lib/server/access/collaboration';
import { databaseError, validationError } from '$lib/server/api/errors';
import { attachmentCreateSchema } from '$lib/server/validation/collaboration.schema';
import { zodFieldErrors } from '$lib/server/validation/foundation.schema';
import { buildThumbnailObjectKey } from '$lib/server/storage/r2';

export const POST: RequestHandler = async (event) => {
	let body: unknown;
	try {
		body = await event.request.json();
	} catch {
		return validationError({ form: 'Request body must be valid JSON.' });
	}

	const parsed = attachmentCreateSchema.safeParse(body);
	if (!parsed.success) return validationError(zodFieldErrors(parsed.error));

	const access = await requireLinkedEntityAccess(event, parsed.data.entity_type, 'manage');
	if ('response' in access) return access.response;

	const organizationId = access.auth.organization.id;
	const belongs = await linkedEntityBelongsToOrganization(
		event.locals.supabase,
		organizationId,
		parsed.data.entity_type,
		parsed.data.entity_id
	);
	if (!belongs) return validationError({ entity_id: 'That record was not found.' });

	// The object key was generated by the presign step and encodes the org/entity it was issued for; a
	// mismatch here means the caller is trying to attach a file to a different record than it was signed for.
	const expectedPrefix = `${organizationId}/${parsed.data.entity_type}/${parsed.data.entity_id}/`;
	if (!parsed.data.object_key.startsWith(expectedPrefix))
		return validationError({ object_key: 'That file was not uploaded for this record.' });

	// The preview must be the one presigned for this exact file, not some other object the caller names.
	const thumbnailObjectKey = parsed.data.thumbnail_object_key ?? null;
	if (thumbnailObjectKey && thumbnailObjectKey !== buildThumbnailObjectKey(parsed.data.object_key))
		return validationError({ thumbnail_object_key: 'That preview does not belong to this file.' });

	const { data, error } = await event.locals.supabase
		.from('attachments')
		.insert({
			organization_id: organizationId,
			entity_type: parsed.data.entity_type,
			entity_id: parsed.data.entity_id,
			note_id: parsed.data.note_id ?? null,
			file_name: parsed.data.file_name,
			mime_type: parsed.data.mime_type,
			size_bytes: parsed.data.size_bytes,
			object_key: parsed.data.object_key,
			thumbnail_object_key: thumbnailObjectKey,
			uploaded_by: access.auth.user.id
		})
		.select()
		.single();
	if (error) return databaseError();

	return json({ attachment: data }, { status: 201 });
};

export const GET: RequestHandler = async (event) => {
	const params = parseLinkedEntityQuery(event.url);
	if (!params) return validationError({ entity_type: 'Provide entity_type and entity_id.' });

	const access = await requireLinkedEntityAccess(event, params.entity_type, 'view');
	if ('response' in access) return access.response;

	const { data, error } = await event.locals.supabase
		.from('attachments')
		.select('*')
		.eq('entity_type', params.entity_type)
		.eq('entity_id', params.entity_id)
		.order('created_at', { ascending: false });
	if (error) return databaseError();

	return json({ attachments: data ?? [] });
};
