-- Communications Stage 6D-3: MMS pricing + secure-link fallback for a picture/file that cannot go as real
-- MMS (a non-image file, or a picture whose sender/destination is not US/Canada). Closes 6D-2's placeholder
-- refusal ("Picture messaging is not available for this number yet.") with the behavior 6D was actually
-- approved for on 2026-09-12: "supported pictures send/arrive as MMS where country/sender/destination allow
-- it; other files use approved secure links; explain why when unavailable."
--
-- Jafar approved 2026-09-16 (asked directly, not guessed): the composer's attach control is always available
-- for any common file, not gated on MMS eligibility; a picture goes as real MMS when eligible, otherwise the
-- text carries a secure link -- same as any other file type. The link never expires, matching how quote and
-- invoice customer links already work (no rotation/expiry infrastructure invented here).
--
-- Money: MMS bills Twilio as one flat unit per message, not per segment (confirmed against Twilio's own
-- pricing pages -- a picture text is priced as "1 MMS" regardless of how much text rides with it, unlike a
-- plain SMS which bills per 153/70-character segment). This adds 'mms' as a second message_unit next to the
-- existing 'segment', publishable through the same Jafar-owned communication_sms_set_retail_rate the SMS
-- segment rate already uses -- no new pricing mechanism.
--
-- The secure link reuses the exact token pattern already proven by quotes/invoices/job reports (256-bit
-- random token, only its SHA-256 hash ever reaches the database, one resolver function, streamed through our
-- own server so no raw storage URL is ever exposed) -- not a new invention. Unlike those, this link is issued
-- automatically at send time inside the enqueue command itself (no staff "create link" action), so the token
-- is generated by the TS caller *before* the RPC call and passed in as part of the attachment payload; the
-- database only ever sees the hash and the ready-made link URL text to embed in the message body.

-- ---------------------------------------------------------------------------------------------------------------
-- 1. Money: widen the message_unit an SMS retail rate can be published for.
-- ---------------------------------------------------------------------------------------------------------------
alter table public.communication_sms_retail_rates
  drop constraint communication_sms_retail_rates_message_unit_check;
alter table public.communication_sms_retail_rates
  add constraint communication_sms_retail_rates_message_unit_check
    check (message_unit in ('segment', 'mms'));

-- ---------------------------------------------------------------------------------------------------------------
-- 2. communication_outbound_attachments gains delivery_mode, so the SMS worker knows which rows to hand to
--    Twilio as MediaUrl (a real MMS photo) versus which rows were only ever described by a link already
--    baked into the frozen message body. Email attachments are always 'inline_media' -- the only channel
--    this distinction has ever applied to is SMS.
-- ---------------------------------------------------------------------------------------------------------------
alter table public.communication_outbound_attachments
  add column delivery_mode text not null default 'inline_media'
    check (delivery_mode in ('inline_media', 'secure_link'));

comment on column public.communication_outbound_attachments.delivery_mode is
  '''inline_media'' rows are sent as the message''s own attachment (email attachment, or an MMS photo). '
  '''secure_link'' rows (SMS only) were never handed to the provider directly -- the customer instead '
  'received a link to public.communication_sms_attachment_access_links baked into the frozen message body.';

-- A tenant-scoped unique key so a later table can foreign-key to (organization_id, id) the same way every
-- other tenant-scoped child table in this schema does, rather than trusting a bare id.
alter table public.communication_outbound_attachments
  add constraint communication_outbound_attachments_organization_id_unique unique (organization_id, id);

-- ---------------------------------------------------------------------------------------------------------------
-- 3. The link itself. One row per attachment that went the secure-link route -- there is never a staff
--    "create link" action to mirror (issued automatically inside the enqueue command), so this table carries
--    no issued_by, no rotation and no expiry, matching Jafar's 2026-09-16 answer.
-- ---------------------------------------------------------------------------------------------------------------
create table public.communication_sms_attachment_access_links (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  delivery_intent_id uuid not null,
  attachment_id uuid not null,
  -- The SHA-256 of a 256-bit random token, as raw bytes -- same shape as quote_access_links.token_hash.
  token_hash bytea not null check (octet_length(token_hash) = 32),
  issued_at timestamptz not null default now(),
  first_viewed_at timestamptz,
  constraint communication_sms_attachment_access_links_token_hash_unique unique (token_hash),
  constraint communication_sms_attachment_access_links_intent_fk
    foreign key (organization_id, delivery_intent_id)
    references public.communication_delivery_intents (organization_id, id) on delete cascade,
  constraint communication_sms_attachment_access_links_attachment_fk
    foreign key (organization_id, attachment_id)
    references public.communication_outbound_attachments (organization_id, id) on delete cascade
);

comment on table public.communication_sms_attachment_access_links is
  'One customer link per SMS attachment that could not go as real MMS media. Issued automatically inside '
  'communication_sms_enqueue_operational_core, not by a staff action -- no expiry, no rotation (Jafar '
  '2026-09-16: matches the no-expiry precedent quote/invoice links already use). Stores only the token hash; '
  'the raw token exists once, in the link text baked into the frozen SMS body.';

create index communication_sms_attachment_access_links_intent_idx
  on public.communication_sms_attachment_access_links (organization_id, delivery_intent_id);

alter table public.communication_sms_attachment_access_links enable row level security;

revoke all on table public.communication_sms_attachment_access_links from public, anon, authenticated;
grant select, insert, update on table public.communication_sms_attachment_access_links to service_role;

-- The public file route's one seam: a token hash in, the file's storage pointer out (or nothing, on any
-- failure -- unknown token and "not found" must look identical to a stranger). Records first_viewed_at on
-- the first successful resolve, same idea as job_report_access_links' own view marker.
create or replace function public.resolve_communication_sms_attachment_access_link(
  supplied_token_hash bytea
) returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  link_row public.communication_sms_attachment_access_links;
  attachment_row public.communication_outbound_attachments;
begin
  if supplied_token_hash is null or octet_length(supplied_token_hash) <> 32 then
    return null;
  end if;

  select * into link_row
  from public.communication_sms_attachment_access_links
  where token_hash = supplied_token_hash;
  if link_row.id is null then
    return null;
  end if;

  select * into attachment_row
  from public.communication_outbound_attachments
  where id = link_row.attachment_id and organization_id = link_row.organization_id;
  if attachment_row.id is null then
    return null;
  end if;

  update public.communication_sms_attachment_access_links
  set first_viewed_at = coalesce(first_viewed_at, now())
  where id = link_row.id;

  return jsonb_build_object(
    'object_key', attachment_row.object_key,
    'mime_type', attachment_row.mime_type,
    'file_name', attachment_row.file_name
  );
end;
$$;

revoke all on function public.resolve_communication_sms_attachment_access_link(bytea)
  from public, anon, authenticated;
grant execute on function public.resolve_communication_sms_attachment_access_link(bytea) to service_role;

-- ---------------------------------------------------------------------------------------------------------------
-- 4. communication_sms_message_snapshots gains raw_body: the composer's own typed text, kept separate from
--    body (the wire text actually segmented and sent, which now may carry an appended link). Idempotent
--    replay must compare against the user's own draft, not the wire text -- a genuine network retry of the
--    same send generates a *new* random token each time (the token is never derived from anything
--    deterministic, to keep it unguessable), so the wire body legitimately differs attempt to attempt even
--    though nothing the user typed changed.
-- ---------------------------------------------------------------------------------------------------------------
alter table public.communication_sms_message_snapshots add column raw_body text;
update public.communication_sms_message_snapshots set raw_body = body where raw_body is null;
alter table public.communication_sms_message_snapshots alter column raw_body set not null;
alter table public.communication_sms_message_snapshots
  add constraint communication_sms_message_snapshots_raw_body_check
    check (char_length(raw_body) between 1 and 1600);

-- The wire body can now exceed the composer's own 1600-character cap by the length of an appended link
-- (roughly APP_URL + '/m/' + a 43-character token); widen its ceiling with headroom rather than compute an
-- exact bound that would break the moment APP_URL changes. The segment-count check (max 10 segments) already
-- refuses anything actually too long to send before this bound would ever bind.
alter table public.communication_sms_message_snapshots
  drop constraint communication_sms_message_snapshots_body_check;
alter table public.communication_sms_message_snapshots
  add constraint communication_sms_message_snapshots_body_check
    check (char_length(body) between 1 and 2000);

comment on column public.communication_sms_message_snapshots.raw_body is
  'The composer''s own typed text, before any secure-link URL was appended for the wire body. Idempotent '
  'replay compares this column, never body, so a legitimately different link per attempt never causes a '
  'false payload-conflict.';

-- ---------------------------------------------------------------------------------------------------------------
-- 5. The enqueue core: fold attachment handling all the way in (drops the separate attach_communication_
--    outbound_sms_media call the wrapper used to make afterwards -- only the core knows the sender's MMS
--    eligibility, and the link text has to be in the body before segments are estimated). Signature widens
--    the trailing p_has_media boolean to p_attachments jsonb (drop+recreate: the argument list genuinely
--    changed, matching every prior stage's own precedent for this).
-- ---------------------------------------------------------------------------------------------------------------
drop function private.attach_communication_outbound_sms_media(uuid, uuid, jsonb);

drop function private.communication_sms_enqueue_operational_core(
  uuid, uuid, uuid, uuid, text, text, text, text, uuid, boolean);

create function private.communication_sms_enqueue_operational_core(
  p_organization_id uuid,
  p_client_id uuid,
  p_client_contact_method_id uuid,
  p_sender_id uuid,
  p_subject text,
  p_body text,
  p_send_kind text,
  p_logical_send_key text,
  p_created_by uuid,
  p_attachments jsonb default '[]'::jsonb
) returns public.communication_delivery_intents
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  recipient public.client_contact_methods;
  recipient_e164 text;
  sender public.communication_sms_sender_identities;
  registration public.communication_sms_registrations;
  outbound record;
  consent text;
  v_encoding text;
  v_segment_count integer;
  rate public.communication_sms_retail_rates;
  cost_minor bigint;
  currency text := 'USD';
  settled bigint;
  reserved bigint;
  promo_balance bigint;
  promo_reserved bigint;
  promo_available bigint;
  purchased_available bigint;
  promo_used bigint;
  purchased_used bigint;
  available timestamptz;
  intent public.communication_delivery_intents;
  existing public.communication_delivery_intents;
  existing_raw_body text;
  source_key text;
  v_attachment jsonb;
  v_delivery_mode text;
  v_effective_body text;
  v_attachment_id uuid;
  v_attachment_bytes bigint;
begin
  -- 1. Shape.
  if p_subject is null or p_subject not in ('service', 'work_updates', 'billing_updates') then
    raise exception 'a send must name a valid operational subject' using errcode = 'P0001';
  end if;
  if p_body is null or char_length(trim(p_body)) = 0 then
    raise exception 'a send needs a message body' using errcode = 'P0001';
  end if;
  if p_send_kind is null or p_send_kind not in ('manual', 'automated') then
    raise exception 'a send must be manual or automated' using errcode = 'P0001';
  end if;
  if p_logical_send_key is null or char_length(trim(p_logical_send_key)) = 0 then
    raise exception 'a send must carry a logical send key' using errcode = 'P0001';
  end if;
  if jsonb_array_length(coalesce(p_attachments, '[]'::jsonb)) > 1 then
    raise exception 'Attach at most one file to a text message.' using errcode = 'check_violation';
  end if;

  -- 2. Resolve the recipient: an active phone on this customer in this organization, normalized to E.164.
  select method.* into recipient
  from public.client_contact_methods method
  join public.clients client
    on client.organization_id = method.organization_id and client.id = method.client_id
  where method.organization_id = p_organization_id
    and method.id = p_client_contact_method_id
    and method.client_id = p_client_id
    and method.kind = 'phone'
    and client.deleted_at is null
  for share of method, client;

  if recipient.id is null then
    raise exception 'Choose an active phone number for this customer.' using errcode = 'foreign_key_violation';
  end if;
  recipient_e164 := '+' || recipient.normalized_value;
  if recipient_e164 !~ '^\+[1-9][0-9]{7,14}$' then
    raise exception 'That customer phone number is not a valid mobile number.' using errcode = 'P0001';
  end if;

  -- 3. Resolve the sending number: the chosen one, or the organization default. Must be a live, SMS-capable
  --    number tied to a registration.
  if p_sender_id is not null then
    select s.* into sender
    from public.communication_sms_sender_identities s
    where s.organization_id = p_organization_id
      and s.id = p_sender_id
      and s.lifecycle_state = 'ready'
      and s.capable_sms
    for share of s;
  else
    select s.* into sender
    from public.communication_sms_sender_identities s
    where s.organization_id = p_organization_id
      and s.is_default_sender
      and s.lifecycle_state = 'ready'
      and s.capable_sms
    for share of s;
  end if;

  if sender.id is null then
    raise exception 'No ready SMS number is available to send from.'
      using errcode = 'object_not_in_prerequisite_state';
  end if;
  if sender.registration_id is null or sender.country_code is null or sender.sender_type is null then
    raise exception 'This SMS number is not fully set up to send yet.'
      using errcode = 'object_not_in_prerequisite_state';
  end if;

  -- 3.5. Delivery mode (Stage 6D-3): a picture goes as real MMS only when both the sender is MMS-capable and
  --      its registered country is US/Canada (Twilio's hard technical limit -- see 6D-2's own header note for
  --      why this is the only country signal this system has). Anything else with an attachment -- a
  --      non-image file, or an image the sender/destination cannot carry as MMS -- gets a secure link instead
  --      of a refusal, per the approved 6D contract. No exception is raised for ineligibility any more.
  if jsonb_array_length(coalesce(p_attachments, '[]'::jsonb)) = 1 then
    v_attachment := p_attachments -> 0;
    if (v_attachment ->> 'mime_type') in ('image/jpeg', 'image/jpg', 'image/png', 'image/gif')
       and sender.capable_mms and sender.country_code in ('US', 'CA') then
      v_delivery_mode := 'inline_media';
    else
      v_delivery_mode := 'secure_link';
    end if;
  end if;

  v_effective_body := case
    when v_delivery_mode = 'secure_link' then p_body || E'\n\n' || (v_attachment ->> 'link_url')
    else p_body
  end;

  select r.* into registration
  from public.communication_sms_registrations r
  where r.organization_id = p_organization_id and r.id = sender.registration_id;
  if registration.id is null then
    raise exception 'This SMS number is not fully set up to send yet.'
      using errcode = 'object_not_in_prerequisite_state';
  end if;

  -- 4. Idempotency: a repeat of the same logical send returns the already-queued intent unchanged; the same
  --    key with a different frozen payload is a conflict. Compared against raw_body (what the user actually
  --    typed), never the wire body -- see this migration's header note on why the wire body can legitimately
  --    differ attempt to attempt for a secure-link send. Return the replay before re-running any live gate.
  select i.* into existing
  from public.communication_delivery_intents i
  where i.organization_id = p_organization_id and i.logical_send_key = trim(p_logical_send_key);

  if existing.id is not null then
    select snap.raw_body into existing_raw_body
    from public.communication_sms_message_snapshots snap
    where snap.delivery_intent_id = existing.id;

    if existing.channel = 'sms'
      and existing.recipient_phone = recipient_e164
      and existing.sms_sender_identity_id = sender.id
      and existing.send_kind = p_send_kind
      and existing_raw_body = p_body then
      return existing;
    end if;
    raise exception 'This message was already queued with different details.' using errcode = 'unique_violation';
  end if;

  -- 5. Readiness and holds in one read.
  select * into outbound
  from public.communication_sms_outbound_state(
    p_organization_id, sender.country_code, sender.sender_type, registration.use_case
  );
  if outbound.state = 'outbound_paused' then
    raise exception 'Outbound SMS is paused for this organization right now.'
      using errcode = 'object_not_in_prerequisite_state';
  elsif outbound.state <> 'ready' then
    raise exception 'This organization is not ready to send SMS yet.'
      using errcode = 'object_not_in_prerequisite_state';
  end if;

  -- 6. Consent for this exact number and this one subject. Unknown or opted-out refuses.
  consent := public.communication_sms_consent_status(
    p_organization_id, p_client_contact_method_id, p_subject
  );
  if consent = 'opted_out' then
    raise exception 'This customer has opted out of text messages.' using errcode = 'P0001';
  elsif consent <> 'opted_in' then
    raise exception 'There is no SMS consent on file for this customer and message type.'
      using errcode = 'P0001';
  end if;

  -- 7. Freeze the segment estimate against the wire body (with any secure link already appended), so the
  --     charge, the "too long to send" refusal and the frozen snapshot all agree on what is actually sent.
  select est.encoding, est.segment_count into v_encoding, v_segment_count
  from public.communication_sms_estimate_segments(v_effective_body) est;
  if v_segment_count > 10 then
    raise exception 'This message is too long to send as one text.' using errcode = 'P0001';
  end if;

  -- 8. Freeze the applicable retail rate and the estimated cost (rounded up so the reservation never
  --    under-holds). A real MMS photo bills as one flat message_unit='mms' charge, matching how Twilio itself
  --    bills a picture text -- per segment only applies to plain text.
  if v_delivery_mode = 'inline_media' then
    select rr.* into rate
    from public.communication_sms_effective_retail_rate(
      sender.country_code, sender.sender_type, 'mms', currency, now()
    ) rr;
    if rate.id is null then
      raise exception 'No picture-message price is published for this destination yet.'
        using errcode = 'object_not_in_prerequisite_state';
    end if;
    cost_minor := ceil(rate.retail_rate_major * 100)::bigint;
  else
    select rr.* into rate
    from public.communication_sms_effective_retail_rate(
      sender.country_code, sender.sender_type, 'segment', currency, now()
    ) rr;
    if rate.id is null then
      raise exception 'No SMS price is published for this destination yet.'
        using errcode = 'object_not_in_prerequisite_state';
    end if;
    cost_minor := ceil(v_segment_count * rate.retail_rate_major * 100)::bigint;
  end if;

  -- 9. Serialize on the organization's credit account and check spendable balance.
  insert into public.communication_sms_credit_accounts (organization_id, currency_code)
  values (p_organization_id, currency)
  on conflict (organization_id) do nothing;

  select settled_balance_minor, reserved_balance_minor into settled, reserved
  from public.communication_sms_credit_accounts
  where organization_id = p_organization_id
  for update;

  promo_balance := public.communication_sms_promotional_balance(p_organization_id);
  select coalesce(sum(reserved_promotional_minor), 0) into promo_reserved
  from public.communication_sms_credit_reservations
  where organization_id = p_organization_id and state in ('reserved', 'submission_unknown', 'settled');
  promo_available := greatest(promo_balance - promo_reserved, 0);
  purchased_available := settled - reserved;

  if promo_available + purchased_available < cost_minor then
    raise exception 'There is not enough SMS balance to send this message.' using errcode = 'P0402';
  end if;

  promo_used := least(cost_minor, promo_available);
  purchased_used := cost_minor - promo_used;

  -- 10. Schedule for quiet hours (now unless inside the window).
  available := public.communication_sms_quiet_hours_available_at(now());

  -- 11. Create the durable send intent.
  begin
    insert into public.communication_delivery_intents (
      organization_id, client_id, client_contact_method_id, channel, logical_send_key,
      recipient_phone, sms_sender_identity_id, send_kind, allowance_class, created_by
    ) values (
      p_organization_id, p_client_id, p_client_contact_method_id, 'sms', trim(p_logical_send_key),
      recipient_e164, sender.id, p_send_kind, 'optional', p_created_by
    )
    returning * into intent;
  exception when unique_violation then
    select i.* into existing
    from public.communication_delivery_intents i
    where i.organization_id = p_organization_id and i.logical_send_key = trim(p_logical_send_key);
    select snap.raw_body into existing_raw_body
    from public.communication_sms_message_snapshots snap
    where snap.delivery_intent_id = existing.id;
    if existing.channel = 'sms'
      and existing.recipient_phone = recipient_e164
      and existing.sms_sender_identity_id = sender.id
      and existing.send_kind = p_send_kind
      and existing_raw_body = p_body then
      return existing;
    end if;
    raise exception 'This message was already queued with different details.' using errcode = 'unique_violation';
  end;

  -- 12. Freeze the wire body (with any link already appended), the raw draft text, encoding and segment count.
  insert into public.communication_sms_message_snapshots (
    delivery_intent_id, organization_id, body, raw_body, encoding, segment_count
  ) values (
    intent.id, p_organization_id, v_effective_body, p_body, v_encoding, v_segment_count
  );

  -- 13. Reserve the estimated cost.
  source_key := 'send:' || trim(p_logical_send_key);
  update public.communication_sms_credit_accounts
  set reserved_balance_minor = reserved_balance_minor + purchased_used,
      updated_at = now()
  where organization_id = p_organization_id;

  insert into public.communication_sms_credit_reservations (
    organization_id, delivery_intent_id, source_key, amount_minor, segment_count,
    reserved_promotional_minor, reserved_purchased_minor
  ) values (
    p_organization_id, intent.id, source_key, cost_minor, v_segment_count,
    promo_used, purchased_used
  );

  -- 14. Persist the attachment (if any) and, for a secure-link delivery, the access link the body already
  --     names. Re-validates size and the caller's own object-key prefix server-side (advisory checks
  --     already ran in TS) -- a real MMS photo keeps 6D-2's own 5 MB/image-only ceiling; anything going out
  --     as a link gets the same 20 MB ceiling every other outbound attachment (email) already uses.
  if v_delivery_mode is not null then
    v_attachment_bytes := (v_attachment ->> 'byte_size')::bigint;
    if v_attachment ->> 'object_key' not like p_organization_id::text || '/outbound-sms-attachments/%' then
      raise exception 'That file does not belong to this business.' using errcode = 'check_violation';
    end if;
    if v_delivery_mode = 'inline_media' and v_attachment_bytes > 5 * 1024 * 1024 then
      raise exception 'A picture must be 5 MB or smaller to send as a text message.'
        using errcode = 'check_violation';
    end if;
    if v_delivery_mode = 'secure_link' and v_attachment_bytes > 20 * 1024 * 1024 then
      raise exception 'A file must be 20 MB or smaller to send as a text message.'
        using errcode = 'check_violation';
    end if;

    insert into public.communication_outbound_attachments (
      organization_id, delivery_intent_id, file_name, mime_type, byte_size, object_key, delivery_mode
    ) values (
      p_organization_id, intent.id, v_attachment ->> 'file_name', v_attachment ->> 'mime_type',
      v_attachment_bytes, v_attachment ->> 'object_key', v_delivery_mode
    )
    on conflict (delivery_intent_id, object_key) do update set delivery_mode = excluded.delivery_mode
    returning id into v_attachment_id;

    if v_delivery_mode = 'secure_link' then
      insert into public.communication_sms_attachment_access_links (
        organization_id, delivery_intent_id, attachment_id, token_hash
      ) values (
        p_organization_id, intent.id, v_attachment_id,
        decode(v_attachment ->> 'access_token_hash', 'hex')
      )
      on conflict (token_hash) do nothing;
    end if;
  end if;

  -- 15. Hand the send to the outbox, scheduled for quiet hours.
  insert into public.communication_outbox_events (
    organization_id, delivery_intent_id, channel, available_at
  ) values (
    p_organization_id, intent.id, 'sms', available
  );

  return intent;
end;
$$;

comment on function private.communication_sms_enqueue_operational_core(
  uuid, uuid, uuid, uuid, text, text, text, text, uuid, jsonb) is
  'The one SMS eligibility/write engine shared by every caller: consent, destination, readiness/holds, '
  'balance, segments/rate, quiet hours, idempotency, delivery-mode resolution (real MMS vs a secure link '
  'baked into the body) and the atomic intent/reservation/snapshot/attachment/outbox write. Takes no actor '
  'and does no permission check -- callers authorize themselves first. Service role only.';

revoke all on function private.communication_sms_enqueue_operational_core(
  uuid, uuid, uuid, uuid, text, text, text, text, uuid, jsonb) from public, anon, authenticated;

-- ---------------------------------------------------------------------------------------------------------------
-- 6. The public, permission-checked wrapper: same widen, same drop+recreate discipline.
-- ---------------------------------------------------------------------------------------------------------------
drop function public.communication_sms_enqueue_operational(
  uuid, uuid, uuid, uuid, uuid, text, text, text, text, boolean);

create function public.communication_sms_enqueue_operational(
  p_organization_id uuid,
  p_actor uuid,
  p_client_id uuid,
  p_client_contact_method_id uuid,
  p_sender_id uuid,
  p_subject text,
  p_body text,
  p_send_kind text,
  p_logical_send_key text,
  p_attachments jsonb default '[]'::jsonb
) returns public.communication_delivery_intents
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
begin
  if p_actor is null then
    raise exception 'a send must record who sent it' using errcode = 'P0001';
  end if;

  if not private.member_has_permission(p_organization_id, p_actor, 'conversations.send')
    or not private.member_has_permission(p_organization_id, p_actor, 'customers.view') then
    raise exception 'You do not have permission to send a customer message.'
      using errcode = 'insufficient_privilege';
  end if;

  return private.communication_sms_enqueue_operational_core(
    p_organization_id, p_client_id, p_client_contact_method_id, p_sender_id,
    p_subject, p_body, p_send_kind, p_logical_send_key, p_actor, p_attachments);
end;
$$;

revoke all on function public.communication_sms_enqueue_operational(
  uuid, uuid, uuid, uuid, uuid, text, text, text, text, jsonb) from public, anon, authenticated;
grant execute on function public.communication_sms_enqueue_operational(
  uuid, uuid, uuid, uuid, uuid, text, text, text, text, jsonb) to service_role;

comment on function public.communication_sms_enqueue_operational(
  uuid, uuid, uuid, uuid, uuid, text, text, text, text, jsonb) is
  'Human-authorized SMS send: checks the actor''s permission, then delegates every live gate (including '
  'delivery-mode resolution) and the atomic write to private.communication_sms_enqueue_operational_core. '
  'Service role only.';

-- ---------------------------------------------------------------------------------------------------------------
-- 7. enqueue_conversation_reply_sms: same signature (target_attachments already jsonb), forwards straight
--    through to the core instead of calling a since-removed separate attach step afterwards.
-- ---------------------------------------------------------------------------------------------------------------
create or replace function public.enqueue_conversation_reply_sms(
  target_organization_id uuid,
  target_actor_user_id uuid,
  target_client_id uuid,
  target_logical_send_key text,
  target_body text,
  target_attachments jsonb default '[]'::jsonb
) returns public.communication_delivery_intents
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  recipient public.client_contact_methods;
  latest_contact_method_id uuid;
  intent public.communication_delivery_intents;
begin
  select client_contact_method_id into latest_contact_method_id
  from (
    select client_contact_method_id, created_at
    from public.communication_delivery_intents
    where organization_id = target_organization_id and client_id = target_client_id and channel = 'sms'
    union all
    select client_contact_method_id, created_at
    from public.communication_inbound_messages
    where organization_id = target_organization_id and client_id = target_client_id and channel = 'sms'
  ) activity
  order by created_at desc
  limit 1;

  select method.* into recipient
  from public.client_contact_methods method
  join public.clients client
    on client.organization_id = method.organization_id and client.id = method.client_id
  where method.organization_id = target_organization_id
    and method.client_id = target_client_id
    and method.kind = 'phone'
    and client.deleted_at is null
    and (latest_contact_method_id is null or method.id = latest_contact_method_id)
  order by method.is_primary desc, method.created_at, method.id
  limit 1
  for share of method, client;

  if recipient.id is null then
    raise exception 'This customer has no active phone number to reply to.' using errcode = 'foreign_key_violation';
  end if;

  intent := public.communication_sms_enqueue_operational(
    target_organization_id, target_actor_user_id, target_client_id, recipient.id,
    null, 'service', target_body, 'manual', target_logical_send_key, target_attachments
  );

  return intent;
end;
$$;

comment on function public.enqueue_conversation_reply_sms(uuid, uuid, uuid, text, text, jsonb) is
  'Resolves the SMS reply recipient from this conversation''s own most recent activity (falling back to the '
  'primary phone), then delegates the send -- including attachment delivery-mode resolution -- straight to '
  'communication_sms_enqueue_operational with subject ''service'' and the organization''s default sender.';

-- ---------------------------------------------------------------------------------------------------------------
-- 8. list_communication_outbound_attachments now must only ever hand the SMS worker a row that is actually
--    supposed to go to Twilio as MediaUrl. A 'secure_link' row was never meant to reach the provider as media
--    at all -- its file is only referenced by the link already baked into the frozen message body -- so
--    without this filter the worker would double-deliver it (once as the link in the text, once as raw MMS
--    media). Email attachments are untouched: they are always 'inline_media' and this function is SMS-only.
--    Return shape is unchanged, so create or replace is enough (no drop+recreate needed).
-- ---------------------------------------------------------------------------------------------------------------
create or replace function public.list_communication_outbound_attachments(
  target_delivery_intent_id uuid
) returns table (file_name text, mime_type text, byte_size bigint, object_key text)
language sql
security definer
set search_path = pg_catalog, public
as $function$
  select
    attachment.file_name,
    attachment.mime_type,
    attachment.byte_size,
    attachment.object_key
  from public.communication_outbound_attachments attachment
  where attachment.delivery_intent_id = target_delivery_intent_id
    and attachment.delivery_mode = 'inline_media'
  order by attachment.created_at, attachment.id;
$function$;
